export const ALL_DATA = [
    {
        day:1,

        title:"Where Wisdom Begins",

        book:"Romans 12:1-8",

        verse: "If my people would but listen to me, . . . how quickly would I subdue their enemies and turn my hand against their foes! ",

        subtitle:"True wisdom is gazing at God",

        insight:"It is vital that we know God’s love and rest comfortably in it. But a true understanding of God’s love begins with an overwhelming awareness of His greatness, holiness, and power as they contrast our own sinful nature. There is nothing more fear-inducing than that. But this is where we must begin. This will shape our self-awareness, our relationships, our work, our prayers—everything we think and do. It will make us wise",

        content:"We’re uncomfortable with the idea of fearing God. We defend Him as One whose love is so great He needs not be feared. As 1 John 4:18 says: “Perfect love drives out fear.” So we redefine fear as “awe” and “reverence.” Yet the Scriptures use the term “fear of God” frequently enough to give us the impression that something more than awe is appropriate. It is the kind of fear that terrified the disciples when they heard God’s voice at the Transfiguration (Matthew 17:6); that overwhelmed Isaiah when he cried out: “Woe to me! . . . I am ruined!” in God’s presence (Isaiah 6:5); and that drove John facedown at the sight of the glorified Son (Revelation 1:17). Why does a God of love tell us that wisdom begins when we fear Him? Because when we approach the Holy One with a casual familiarity, we are not living in reality. We do not take Him as seriously as we ought, and we do not take our sin as seriously as we ought. Fear—not of punishment but of the overwhelming greatness of God—sees Him correctly. When we stand on the edge of the vast, bottomless chasm that separates us from Him, and we behold the immeasurable expense He paid to bridge that chasm, we experience fear. Fear of what would have been if we had never known the gospel. Fear of our own unworthiness. Fear of the absolute dedication to Him that is now required of us. When this fear grips us, we begin to understand the enormity of the gospel and of our God. That understanding begins to rearrange our lives. And that is what wisdom is all about.",

        
    },
    {
        day:2,

        title:"Wise Worship ",

        book:"Romans 12:1-2",

        verse:"I urge you, brothers, in view of God’s mercy, to offer your  bodies as living sacrifices, holy and pleasing to God—this is your spiritual act of worship",

        subtitle:"True wisdom is gazing at God",

        insight:"It is vital that we know God’s love and rest comfortably in it. But a true understanding of God’s love begins with an overwhelming awareness of His greatness, holiness, and power as they contrast our own sinful nature. There is nothing more fear-inducing than that. But this is where we must begin. This will shape our self-awareness, our relationships, our work, our prayers—everything we think and do. It will make us wise",
        content:"IN WORD Wisdom begins with basing one’s life on reality. “The fear of the LORD is the beginning of wisdom” (Proverbs 9:10). Why? Because fear of the Lord is based on a true understanding of who we really are and who God really is. But there is a next step. Wisdom doesn’t begin and end with fear; it continues into worship. When we really understand who God is, the natural response is to offer Him whatever we can get our hands on—and all we have is ourselves. All of those in the Bible who encountered the living God in His glory fell on their face in worship. Like Isaiah, they would offer themselves (Isaiah 6:8). If we have not yet gotten to that point of laying ourselves on the altar before Him—without reservation—we have not yet encountered the living God. His glory prompts sacrifice. It is the only wise, intelligent, reasonable response to the magnitude of His goodness. IN DEED We often think of worship as words and songs that come out of our mouths. It is so much more. It is a lifestyle, a sacrificial way of living that acknowledges every moment of every day that there is One far more worthy of our allegiance than ourselves. When His interests consistently supercede ours, and we act accordingly, we are worshiping. Imagine yourself in the throne room of God. See the altar at His feet. Get on it. Lay yourself out before Him and say to Him: “I am Yours. Do with me as You will. I give up my right to govern myself, because You are far more worthy to do it, and You will never do me harm. I exist for Your purposes, and for Yours alone.” Do this every morning, then live out your day mindful of whose you are. In light of who He is, this is true worship. And true worship is the wisest thing we can do."
        
    },
    {
        day:3,
        title:"A Higher Mind",
        book:"1 Corinthians 2:6-16",
        verse:"The truly wise are those whose souls are in Christ.",
        subtitle:"We have the mind of Christ.",
        content:"IN WORD At first glance, Paul’s claim is boastful. It would not go over well in our “politically correct” culture of today. It probably did not go over well in the Corinthian culture then, except within the church. There, it would have been a treasured truth and an amazing revelation. So it is with us. It is almost unthinkable: the mind of the One through whom the entire universe was created, the fount of all wisdom, is available to us. We are not limited to human reasoning. We are not bound by the limitations of history’s greatest thinkers, who, while often exceeding human standards of intelligence, have all fallen drastically short of discovering eternal truth by natural means. No, we have a supernatural access to ultimate reality from an eternal perspective. We know the direction of history and where it is leading; we know how to escape this fallen world; and we know who holds all power in the palm of His right hand. This vast, incomprehensible treasure is ours—if we will accept it. That’s our problem. We often resort to lesser means of wisdom because we’re unaware that the mind of Christ is accessible, or we’re unable to believe such an extravagant promise. But if we can’t believe it, we can’t have it. The mind of Christ is ours through the Spirit of God, who comes to us only through faith. The Spirit searches the deep things of God (v. 10) and reveals them to His people. Such things are foolish to the world, but they are truth nonetheless—truth that we can know and base our lives on. IN DEED You have your own mind. You also have Christ’s. Which would you rather depend on? Begin each day by disavowing your own wisdom. We must acknowledge that we do not have the understanding to make the decisions we will face each day. We do not know all the details or future implications of any decision. But God does, and He makes His wisdom available. Acknowledge your utter dependence on the mind of Christ, ask for His wisdom, and believe."
    },
    {
        day:4,
        title:"Driven by Instinct ",
        book:" JUDE 18",
        verse:"In the last times there will be scoffers who will follow their own ungodly desires.",
        subtitle:"Let temporal things serve your use, but the eternal be the object of your desire.",
        content:"IN WORD Guidance is always a pressing issue for the Christian. Pick a moment in your life—any moment at all— and it is likely that you have needed guidance on some critical area at that particular moment. We are always in need of direction, and most of us are acutely aware of that need. The unbeliever, as this passage says, is a slave to instinct and self. Those who do not follow God must follow their own internal logic. And that logic is a mess of distorted perspectives, most often driven by self. The self-guided person will make decisions based on emotional needs, cravings for self-esteem, physical impulses, and present-life planning. There is nothing eternal about their choices, no urge to submit to their Creator, no consistent willingness to put others’ needs ahead of their own desires. Even in their highest moral behavior, they are driven from within, where the Spirit does not dwell. We, too, often lapse into instinctual decision making. Though we want God’s guidance and ask for it, we often do not wait for it. We make decisions based on what our internal logic tells us. Is that logic guided by the Spirit? Or do we serve our own emotional needs, self-esteem cravings, physical impulses, and present-life interests? We are inhabited by God’s wise, eternal Spirit. But are we driven by Him?IN DEED When we are driven by our own internal impulses and reasoning, we are settling for second best. Even when those instincts are shaped by years of discipleship, they are still subject to sin and deception. We can use them to God’s glory, but we can’t trust them. They must always be submitted to the guiding mind of God. We do not need to follow the patterns of this world. We are not left to figure things out on our own. We are not ruled by our base desires, or even by our noble ones. We have not been abandoned to our own moral codes and higher philosophies. We are called to follow our Leader. We must submit our instincts to Him and follow Him diligently."   
    } ,
    {
        day:5,
        title:"Guided by God",
        book:"PSALM 81:13-14",
        verse:"If my people would but listen to me, . . . how quickly would I subdue their enemies and turn my hand against their foes! ",
        subtitle:"If God’s will is your will and if He always has His way [with you], then you always have your way also.",
        content:"IN WORD The hardest aspect of the Christian life is to learn to submit to God in all things. His yoke is easy, but remembering to be bound by it is difficult. We worship Him for His goodness, we thank Him for His love, we pledge to be His disciples, and we ask Him for His wisdom. All the while, the nuts and bolts of following Him are hard to grasp. When it comes to making decisions, we still like our independence. What is it about our independence that so intrigues us? Why are we so captivated with our decision-making powers? Why, even when we know that a sense of autonomy is Satan’s specialty and the root of our sin, do we insist on maintaining little pieces of it in various corners of our lives? Why, when God tells us one thing and our internal compulsions tell us another, do we often choose the compulsions? What does that say about our trust in God? That’s what the fall of man in the Garden of Eden was all about: mistrusting God and seeking our own interests. And that’s still what sin is all about. When we choose our own will over God’s, we’re mistrusting Him and trusting ourselves. What an absurdity! We forget the most basic of all biblical teaching: God’s will is in our best interest. IN DEED Are you convinced of that? The Christian life will be a struggle until we know deep down in our hearts that His commands—even the hard ones—are ultimately for our benefit. We can be sure that the best way to seek our own self-centered interests is to be entirely God-centered. In this paradox, godliness and the self-life meet. Or, as Jesus said, “Whoever loses his life will preserve it” (Luke 17:33). Our happiness is deeper and richer when we listen to Him. In that sense, it is a self-fulfilling act to forsake our own will and submit to His. Submission seems so noble, but we have a lot at stake in it. When we serve Him, we serve ourselves. Believe that wholeheartedly, and see what happens." 
    } ,
    {
        day:6,
        title:"Not Your Own",
        book:"1 CORINTHIANS 6:19-20",
        verse:"You are not your own you were bought at a price.",
        subtitle:"The condition for gaining God’s full blessing is absolute surrender to Him.",
        content:"IN WORD Life is a series of decisions. Some of them are relatively minor, others have lasting impact. We often act on the minor decisions—what to eat, what to wear, whom to talk to—out of our natural behavior patterns, giving them little thought. With the serious choices—which job to take, where to live, and the like—we weigh pros and cons and try to determine the right course of action. In any case, we are likely to forget an important backdrop to our decision making: We are not our own. We belong to God. Isn’t this easy to forget? We tend to approach life with a certain autonomy, as though we are independent individuals with a responsibility to acknowledge God in worship and sacrifice. But God wants a deeper worship in our lives. Rather than living independently of Him while giving Him our respect, He wants us to live dependently on Him with awareness that every action, every thought, every impulse is to fit into His purposes. We must not act—or even breathe— without this awareness. We have been bought. We are His. Some might consider this the equivalent of slavery or servitude. Paul always did (Romans 1:1; Galatians 1:10; Philippians 1:1; Titus 1:1), regardless of whether he was free or in prison. But it is a joyful service that carries with it no sense of oppression. How could it? Our Master is the epitome of benevolence. He knows our innermost being and is zealously intent on fulfilling us. The key for us is living with the knowledge that we are owned and operated by the most loving and qualified Owner possible. IN DEED The Christian who lives with this wisdom— that we are owned by Another—is a Christian profoundly changed. Our decisions are affected, our character is reformed, and our load is lightened. We lose the right to ourselves, but we also lose the burden of self-rule. It is a wonderfully freeing truth. Everything about us is the concern of Someone else."
    } ,
    {
        day:7,
        title:"The Available Mind of God ",
        book:"JAMES 1:5",
        verse:"If any of you lacks wisdom, he should ask God, who gives generously to all without finding fault.",
        subtitle:"There is a deep wisdom inaccessible to the wise and prudent, but disclosed to babes.",
        content:"IN WORD Why would God set up a process for us to gain wisdom? Why would He not just give it to us? Because asking for His wisdom and receiving it brings us into relationship with Him. The wisdom we receive is not information imparted, but character learned. We observe who He is and we learn to behave like Him. We come to know Him better in the process. His wisdom is readily available, but we must ask. Have you found yourself needing guidance in a given situation? Our usual tendency is to pray for direction. But God has a better way. Pray for wisdom, and the direction will become clear. If we were to pray for direction, God could only answer by giving us information. But if we pray for wisdom, God answers by giving us His own mind. We are prone to call upon God for wisdom only when we find ourselves in a difficulty. But far from being a onetime request in a moment of need, this verse hints at an ongoing process. It isn’t that we ask for wisdom one day when we’re at our wit’s end; we are to ask for wisdom daily because we will find ourselves at wit’s end sooner or later. God’s provision of His mind is often given in advance. It is more than instructions for a way to go; it is training for a way of life. IN DEED Do you need direction? Guidance? Wisdom from above? The crucial step, often neglected, is to ask. How often we try to figure things out on our own! How often we ask others for advice before we ask God! Ask Him now. Ask often. Make the asking a regular part of your life. Don’t wait until trouble comes; learn the mind of God now. He offers it generously."
    } ,
    {
        day:8,
        title:"The Available Mind of God ",
        book:"JAMES 1:5",
        verse:"If any of you lacks wisdom, he should ask God, who gives generously to all without finding fault.",
        subtitle:"There is a deep wisdom inaccessible to the wise and prudent, but disclosed to babes.",
        content:"IN WORD Why would God set up a process for us to gain wisdom? Why would He not just give it to us? Because asking for His wisdom and receiving it brings us into relationship with Him. The wisdom we receive is not information imparted, but character learned. We observe who He is and we learn to behave like Him. We come to know Him better in the process. His wisdom is readily available, but we must ask. Have you found yourself needing guidance in a given situation? Our usual tendency is to pray for direction. But God has a better way. Pray for wisdom, and the direction will become clear. If we were to pray for direction, God could only answer by giving us information. But if we pray for wisdom, God answers by giving us His own mind. We are prone to call upon God for wisdom only when we find ourselves in a difficulty. But far from being a onetime request in a moment of need, this verse hints at an ongoing process. It isn’t that we ask for wisdom one day when we’re at our wit’s end; we are to ask for wisdom daily because we will find ourselves at wit’s end sooner or later. God’s provision of His mind is often given in advance. It is more than instructions for a way to go; it is training for a way of life. IN DEED Do you need direction? Guidance? Wisdom from above? The crucial step, often neglected, is to ask. How often we try to figure things out on our own! How often we ask others for advice before we ask God! Ask Him now. Ask often. Make the asking a regular part of your life. Don’t wait until trouble comes; learn the mind of God now. He offers it generously."
    } ,

]



